name: Lines count

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@0.3.1
      with : 
        fail_on_error: true 
