name: Lines count

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check class file length > 500
      run: cd ./Backend/src/main/java
           git ls-files | xargs wc --l | sort -rn | awk '$1 > 500'
