name: Lines count

on:
  push:
    branches:
    - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check class file length - Backend
      working-directory: ./Backend/src/main
      run: git ls-files | xargs wc -l | sort -r | awk '$1 > 500'
    - name: Count files
      id: step1
      run: gradle builddd
  work:
     runs-on: ubuntu-latest
     needs: check
     steps:
      - run: gradle build
      
      

    

