name: Lines count

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    - name: Check class file length - Backend
      working-directory: ./Backend/src/main
      run: git ls-files | xargs wc --l | sort -rn | awk '$1 > 500'
    - name: Count files
      id: step1
      run: git ls-files | xargs wc -l | awk '$1 > 500'| tail -n +3 | wc -l
    - name: Check run status
      if: steps.step1.outputs > 0
      run: exit 1

