name: Lines count

on:
  push:
    branches:
    - main

jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Check class file length - Backend
      working-directory: ./Backend/src/main
      run: git ls-files | xargs wc -l | sort -r | awk '$1 > 500'
    - name: Build failure
      if: git ls-files | xargs wc -l | sort -r | awk '$1 > 500'| tail -n +2 | wc -l == 0
      run: /gradlew builddbb
    
         
      
  
