name: Lines count

on:
  push:
    branches:
    - main

jobs:
  check:
    defaults:
      run:
        working-directory: ./Backend/src/main
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.count }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
    - name: Check class file length - Backend
      run: git ls-files | xargs wc -l | sort -rn | awk '$1 > 100000'
    - name: Job action
      id: test
      run : echo ::set-output name=key::$(git ls-files | xargs wc -l | sort -r | awk '$1 > 100000'| tail -n +2 | wc -l)
    - name: Job count
      if: steps.test.outputs.key > 0
      run: |
       echo "THE CLASSES LISTED CROSS THE MAXIMUM ALLOWED LIMIT"
       gradlew build
  build:
     runs-on: ubuntu-latest
     defaults:
      run:
        working-directory: ./Backend
     needs: check
     steps:
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
     - name: Build with Gradle
       run: ./gradlew build
  
