name: Lines count

on:
  push:
    branches:
    - main

jobs:
  check:
    defaults:
      run:
        working-directory: ./Backend/src/main
    runs-on: ubuntu-latest
    steps:
    - name: Files having 500+ lines
      run: git ls-files | xargs wc -l | sort -rn | awk '$1 > 500'
    - name: Check class file length - Backend 
      id: line_count
      run : echo ::set-output name=key::$(git ls-files | xargs wc -l | sort -r | awk '$1 > 500'| tail -n +2 | wc -l)
    - name: Count of files having 500+ lines
      if: steps.line_count.outputs.key > 0
      run: echo "THE CLASSES LISTED CROSS THE MAXIMUM ALLOWED LIMIT"
  build:
     runs-on: ubuntu-latest
     defaults:
      run:
        working-directory: ./Backend
     needs: check
     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
        java-version: 1.8
     - name: Build with Gradle
       run: ./gradlew build
  
