name: Lines count

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:

    - uses: actions/checkout@v2
    - name: Check class file length - Backend
      working-directory: ./Backend/src/main
      run: git ls-files | xargs wc -l | sort -r | awk '$1 > 500'
    - name: Count files
      working-directory: ./Backend/src/main
      id: step1
      run: git ls-files | xargs wc -l | sort -r | awk '$1 > 500'| tail -n +2 | wc -l
    - name: Job action
      id: step2
      if: steps.step1.outputs > 0
      run: exit 1
    - name: Build application
      if: steps.step2.exitcode == 0      
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
  
