name: Lines count

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check class file length - Backend
      working-directory: cd ./Backend/src/main/java
      run: git ls-files | xargs wc --l | sort -rn | awk '$1 > 500'
