name: Lines count

on:
  push:
    branches:
    - main

jobs:
  build:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
    - name: Check class file length - Backend
      run: |
        cd actions_demo/Backend/src/main/java
        git ls-files | xargs wc -l | sort -r | awk '$1 > 500'
        if [(git ls-files | xargs wc -l | sort -r | awk '$1 > 500'| tail -n +2 | wc -l) > 0] then exit 1; fi
    
