name: Lines count

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    defaults:
      run:
        working-directory: ./Backend/src/main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
    - name: Files having 500+ lines
      run: git ls-files | xargs wc -l | sort -rn | awk '$1 > 1000000'
    - name: Check class file length - Backend 
      id: line_count
      run : echo ::set-output name=key::$(git ls-files | xargs wc -l | sort -r | awk '$1 > 1000000'| tail -n +2 | wc -l)
    - name: Count of files having 500+ lines
      if: steps.line_count.outputs.key > 0
      run: |
       echo "THE CLASSES LISTED CROSS THE MAXIMUM ALLOWED LIMIT"
       end task
  build:
     runs-on: ubuntu-latest
     defaults:
      run:
        working-directory: ./Backend
     needs: check
     steps:
      - name: Checks passed
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: gitnotification.lattice@gmail.com
          password: Lattice@123
          subject: Github Actions result - Class length
          body: Build job of the pull request number - ${{ github.event.number }} of ${{github.repository}}, branch - ${{ github.head_ref }} created by - ${{ github.event.pull_request.user.login }} completed successfully!
          to: rao.samriddha@gmail.com
          from: gitnotification.lattice@gmail.com
          content_type: text/html
