name: CI 
on: push 
jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Get commit
      id: commit
      run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> ./commit.txt
